# DataSource Config
server:
  port: 8888
spring:
  application:
    name: hw-search
  data:
    elasticsearch:
      cluster-name: kobe
      cluster-nodes: 47.106.38.101:9300
      repositories:
        enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka/