# DataSource Config
spring:
  application:
    name: hw-blog
  profiles:
    active: dev
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/homework
    username: root
    password: admin
  redis:
    sentinel:
      master: mymaster
      nodes: 47.106.38.101:26379,47.106.38.101:26380
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka/